export const user = {
  // Post
  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_LOADING: "LOGIN_USER_LOADING",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
  LOGIN_USER_RESET: "LOGIN_USER_RESET",
};
